//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Users = newUsersTable("public", "users", "")

type usersTable struct {
	postgres.Table

	//Columns
	ID               postgres.ColumnInteger
	Email            postgres.ColumnString
	StripeCustomerID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn               = postgres.IntegerColumn("id")
		EmailColumn            = postgres.StringColumn("email")
		StripeCustomerIDColumn = postgres.StringColumn("stripe_customer_id")
		allColumns             = postgres.ColumnList{IDColumn, EmailColumn, StripeCustomerIDColumn}
		mutableColumns         = postgres.ColumnList{EmailColumn, StripeCustomerIDColumn}
	)

	return usersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		Email:            EmailColumn,
		StripeCustomerID: StripeCustomerIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
