POST http://localhost:8080/ HTTP/1.1
content-type: application/json
idempotency-key: key123
http-authorization: local.user@email.com

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}