//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AuditRecords struct {
	ID           int64 `sql:"primary_key"`
	Action       string
	CreatedAt    time.Time
	Data         string
	OriginIP     string
	ResourceID   int64
	ResourceType string
	UserID       int64
}
