//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type IdempotencyKeys struct {
	ID             int64 `sql:"primary_key"`
	CreatedAt      time.Time
	IdempotencyKey string
	LastRunAt      time.Time
	LockedAt       *time.Time
	RequestMethod  string
	RequestParams  string
	RequestPath    string
	ResponseCode   *int32
	ResponseBody   *string
	RecoveryPoint  string
	UserID         int64
}
