//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Rides struct {
	ID               int64 `sql:"primary_key"`
	CreatedAt        time.Time
	IdempotencyKeyID *int64
	OriginLat        float64
	OriginLon        float64
	TargetLat        float64
	TargetLon        float64
	StripeChargeID   *string
	UserID           int64
}
