// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rafael-piovesan/go-rocket-ride/v2/entity"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Ride is an autogenerated mock type for the Ride type
type Ride struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *Ride) Create(_a0 context.Context, _a1 *entity.IdempotencyKey, _a2 *entity.Ride) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.IdempotencyKey, *entity.Ride) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRide creates a new instance of Ride. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRide(t testing.TB) *Ride {
	mock := &Ride{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
