// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rafael-piovesan/go-rocket-ride/entity"
	mock "github.com/stretchr/testify/mock"
)

// RideUseCase is an autogenerated mock type for the RideUseCase type
type RideUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, ik, rd
func (_m *RideUseCase) Create(ctx context.Context, ik *entity.IdempotencyKey, rd *entity.Ride) error {
	ret := _m.Called(ctx, ik, rd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.IdempotencyKey, *entity.Ride) error); ok {
		r0 = rf(ctx, ik, rd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
