// Code generated by sqlc. DO NOT EDIT.
// source: staged_job.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createStagedJob = `-- name: CreateStagedJob :one
INSERT INTO staged_jobs(
	job_name,
	job_args
)
VALUES ($1, $2)
RETURNING id, job_name, job_args
`

type CreateStagedJobParams struct {
	JobName string
	JobArgs json.RawMessage
}

func (q *Queries) CreateStagedJob(ctx context.Context, arg CreateStagedJobParams) (StagedJob, error) {
	row := q.db.QueryRowContext(ctx, createStagedJob, arg.JobName, arg.JobArgs)
	var i StagedJob
	err := row.Scan(&i.ID, &i.JobName, &i.JobArgs)
	return i, err
}
