name: Lint and Tests

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Get dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        type: ["unit", "integration"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Get dependencies
        run: go mod download

      - name: Tests
        run: go test -tags=${{ matrix.type }} -v ./...