// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"

	datastore "github.com/rafael-piovesan/go-rocket-ride/v2/datastore"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Atomic provides a mock function with given fields: _a0, _a1
func (_m *Store) Atomic(_a0 context.Context, _a1 datastore.AtomicBlock) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, datastore.AtomicBlock) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewStore(t testing.TB) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
