// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	uow "github.com/rafael-piovesan/go-rocket-ride/v2/datastore/uow"
)

// UnitOfWorkBlock is an autogenerated mock type for the UnitOfWorkBlock type
type UnitOfWorkBlock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: store
func (_m *UnitOfWorkBlock) Execute(store uow.UnitOfWorkStore) error {
	ret := _m.Called(store)

	var r0 error
	if rf, ok := ret.Get(0).(func(uow.UnitOfWorkStore) error); ok {
		r0 = rf(store)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUnitOfWorkBlock creates a new instance of UnitOfWorkBlock. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnitOfWorkBlock(t testing.TB) *UnitOfWorkBlock {
	mock := &UnitOfWorkBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
