// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	uow "github.com/rafael-piovesan/go-rocket-ride/v2/datastore/uow"
)

// UOWBlock is an autogenerated mock type for the UOWBlock type
type UOWBlock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: store
func (_m *UOWBlock) Execute(store uow.UOWStore) error {
	ret := _m.Called(store)

	var r0 error
	if rf, ok := ret.Get(0).(func(uow.UOWStore) error); ok {
		r0 = rf(store)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUOWBlock creates a new instance of UOWBlock. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUOWBlock(t testing.TB) *UOWBlock {
	mock := &UOWBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
